
name: Build wheels
on: [push]

jobs:

  manylinux-27:

    strategy:
      matrix:
        python-version: [2.7]

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
    - name: Build
      run: |
        python setup.py bdist_wheel
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-manylinux-27
        path: dist

  manylinux-35:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        /opt/python/cp35-cp35m/bin/python -m pip install --upgrade pip
        /opt/python/cp35-cp35m/bin/python -m pip install setuptools wheel
    - name: Build
      run: |
        /opt/python/cp35-cp35m/bin/python setup.py bdist_wheel
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-manylinux-35
        path: dist

  manylinux-36:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        /opt/python/cp36-cp36m/bin/python -m pip install --upgrade pip
        /opt/python/cp36-cp36m/bin/python -m pip install setuptools wheel
    - name: Build
      run: |
        /opt/python/cp36-cp36m/bin/python setup.py bdist_wheel
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-manylinux-36
        path: dist

  manylinux-37:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        /opt/python/cp37-cp37m/bin/python -m pip install --upgrade pip
        /opt/python/cp37-cp37m/bin/python -m pip install setuptools wheel
    - name: Build
      run: |
        /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-manylinux-37
        path: dist

  manylinux-38:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        /opt/python/cp38-cp38/bin/python -m pip install --upgrade pip
        /opt/python/cp38-cp38/bin/python -m pip install setuptools wheel
    - name: Build
      run: |
        /opt/python/cp38-cp38/bin/python setup.py bdist_wheel
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-manylinux-38
        path: dist
